User nobody
Group nogroup
Port 8888
Listen 0.0.0.0
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Info
LogFile "/var/log/tinyproxy/tinyproxy.log"
PidFile "/run/tinyproxy/tinyproxy.pid"
MaxClients 100
Allow 0.0.0.0/0
ViaProxyName "tinyproxy"
DisableViaHeader Yes